services:
  - type: web
    name: gift-website-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # 在 Render.com 控制台中设置
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false 